### PR TITLE
List trash items 

### PR DESCRIPTION
**Pull request by chinghochow**
Not working until move an invoice to trash is implemented, intended behaviour.
Implementation and tests are complete, waiting for move an invoice to trash to be implemented to test and merge.

### CODE REVIEW

**Comment by chinghochow** [comment]
Includes fixes for moving invoice to trash route

**Comment by anemonade** [comment]
Optional changes:
- Add testing for an empty token
- Test for correct invoice name and invoice date (I think date could be updated to the format shown in swagger)

**Comment by chinghochow** [comment]
optional changes noted, will add

**Comment by anemonade** [comment]
Might be more readable to add beforeEach to the tests, otherwise approved

**Pull request merged**
